// Spectrum: The No Hassle Colorpicker
// https://github.com/bgrins/spectrum
// Author: Brian Grinstead
// License: MIT
// Requires: jQuery, spectrum.css
(function(x,e){function Q(a,b){var c=t({},B,a);c.callbacks={move:n(c.move,b),change:n(c.change,b),show:n(c.show,b),hide:n(c.hide,b),beforeShow:n(c.beforeShow,b)};return c}function p(a,b){function c(a){if(j.showPallet){var b=[];I={};for(var c=0;c<a.length;c++){var d=tinycolor(a[c]).toHexString();I.hasOwnProperty(d)||(I[d]=b.push(a[c])-1)}u=b.slice(0,j.maxPalletSize);R.html(s(u,void 0))}}function d(){k.addClass("spectrum-dragging")}function f(){k.removeClass("spectrum-dragging")}function g(){o(J.val())}
function q(){if(!C&&y.beforeShow(r())!==!1){S||(S=!0);for(var a=0;a<v.length;a++)v[a].hide();C=!0;e(K).bind("click touchstart",h);e(x).bind("resize",Y);D.addClass("spectrum-active");k.show();Z();m();$=r();y.show(r())}}function h(){if(C&&!j.flat){C=!1;e(K).unbind("click touchstart",h);e(x).unbind("resize",Y);D.removeClass("spectrum-active");k.hide();var a=r();u.push(a.toHexString());c(u);aa||p();y.hide(a)}}function o(a){a=tinycolor(a).toHsv();E=a.h;L=a.s;M=a.v;m()}function r(){return tinycolor({h:E,
s:L,v:M})}function m(){n();var a=tinycolor({h:E,s:1,v:1});N.css("background-color",a.toHexString());a=r().toHexString();ea.css("background-color",a);F&&J.val(a);S&&aa&&p();j.showPallet&&R.html(s(u,I[a]))}function n(){var a=L*O,b=z-M*z;a=Math.max(-w,Math.min(O-w,a-w));b=Math.max(-w,Math.min(z-w,b-w));ba.css({top:b,left:a});ca.css({top:E*t-B})}function p(){var a=r();F&&A.val(a.toHexString());y.change(a)}function Z(){O=N.width();z=N.height();w=ba.height();T.width();t=T.height();slideHelperHelperHeight=
ca.height();j.flat||k.offset(G(k,da));n()}var j=Q(b,a),y=j.callbacks,Y=i(Z,100),C=!1,O=0,z=0,w=0,t=0,B=0,E=0,L=0,M=0,u=j.pallet.slice(0),I={},K=a.ownerDocument,fa=K.body,A=e(a),k=e(U,K).addClass(j.theme),N=k.find(".spectrum-color"),ba=k.find(".spectrum-drag-helper"),T=k.find(".spectrum-slide"),ca=k.find(".spectrum-slide-helper"),J=k.find(".spectrum-input"),R=k.find(".spectrum-pallet-container"),ga=k.find(".spectrum-cancel"),ha=k.find(".spectrum-choose"),F=A.is("input"),aa=F&&(j.changeOnMove||j.flat),
V=F&&!j.flat,D=V?e(H).addClass(j.theme):e([]),da=V?D:A,ea=D.find(".spectrum-preview"),W=j.color||F&&A.val(),$=!1,S=!1;(function(){e.browser.msie&&k.find("*:not(input)").attr("unselectable","on");k.toggleClass("spectrum-flat",j.flat);k.toggleClass("spectrum-input-disabled",!j.showInput);k.toggleClass("spectrum-pallet-disabled",!j.showPallet);V&&A.hide().after(D);j.flat?A.after(k).hide():e(fa).append(k.hide());da.bind("click touchstart",function(a){C?h():q();a.stopPropagation();e(a.target).is("input")||
a.preventDefault()});k.click(l);J.change(g);J.keydown(function(a){a.keyCode==13&&g()});ga.click(function(){o($);h()});ha.click(function(){h()});P(T,function(a,b){E=b/t;m();y.move(r())},d,f);P(N,function(a,b){L=a/O;M=(z-b)/z;m();y.move(r())},d,f);W&&(o(W),u.push(W));c(u);j.flat&&q();R.delegate("span","click",function(){o(e(this).css("background-color"))})})();var X={show:q,hide:h,set:o,get:r};X.id=v.push(X)-1;return X}function G(a,b){var c=a.outerWidth(),d=a.outerHeight();b.outerWidth();var f=b.outerHeight(),
g=a[0].ownerDocument,q=g.documentElement.clientWidth+e(g).scrollLeft();g=g.documentElement.clientHeight+e(g).scrollTop();var h=b.offset();h.top+=f;h.left-=Math.min(h.left,h.left+c>q&&q>c?Math.abs(h.left+c-q):0);h.top-=Math.min(h.top,h.top+d>g&&g>d?Math.abs(d+f-6):6);return h}function l(a){a.stopPropagation()}function n(a,b){var c=Array.prototype.slice,d=c.call(arguments,2);return function(){return a.apply(b,d.concat(c.call(arguments)))}}function P(a,b,c,d){function f(a){a.stopPropagation&&a.stopPropagation();
a.preventDefault&&a.preventDefault();a.returnValue=!1}function g(c){if(o){if(n&&!(document.documentMode>=9)&&!c.button)return q();var d=c.originalEvent.touches,g=Math.max(0,Math.min((d?d[0].pageX:c.pageX)-i.left,m));d=Math.max(0,Math.min((d?d[0].pageY:c.pageY)-i.top,l));p&&f(c);b.apply(a,[g,d])}}function q(){o&&(e(h).unbind(j),d.apply(a,arguments));o=!1}b=b||function(){};c=c||function(){};d=d||function(){};var h=a.ownerDocument||document,o=!1,i={},l=0,m=0,n=e.browser.msie,p="ontouchstart"in x,j={};
j.selectstart=f;j.dragstart=f;j[p?"touchmove":"mousemove"]=g;j[p?"touchend":"mouseup"]=q;e(a).bind(p?"touchstart":"mousedown",function(b){if(!(b.which?b.which==3:b.button==2)&&!o&&c.apply(a,arguments)!==!1)o=!0,l=e(a).height(),m=e(a).width(),i=e(a).offset(),e(h).bind(j),p?f(b):g(b)})}function i(a,b,c){var d;return function(){var f=this,g=arguments,e=function(){d=null;a.apply(f,g)};c&&clearTimeout(d);if(c||!d)d=setTimeout(e,b)}}function t(a){for(var b=Array.prototype.slice.call(arguments,1),c=0;c<
b.length;c++){var d=b[c],f;for(f in d)d[f]!==void 0&&(a[f]=d[f])}return a}var B={color:!1,flat:!1,showInput:!1,changeOnMove:!0,beforeShow:function(){},move:function(){},change:function(){},show:function(){},hide:function(){},showPallet:!1,maxPalletSize:12,theme:"spectrum-dark",pallet:["white","black"]},v=[],m=typeof e!="undefined",H="<div class='spectrum-replacer spectrum-cf'><div class='spectrum-preview'></div><div class='spectrum-dd'>&#9660;</div></div>",U=function(){var a="";if(e.browser.msie)for(var b=
1;b<9;b++)a+="<div class='spectrum-ie-"+b+"'></div>";return["<div class='spectrum-container'><div class='spectrum-top'><div class='spectrum-fill'></div><div class='spectrum-top-inner'><div class='spectrum-color'><div class='spectrum-saturation'><div class='spectrum-value'><div class='spectrum-drag-helper'></div></div></div></div><div class='spectrum-slide'><div class='spectrum-slide-helper'></div>",a,"</div></div></div><br style='clear:both;' /><div class='spectrum-pallet-container spectrum-cf'></div><div class='spectrum-input-container spectrum-cf'><input class='spectrum-input' type='text' spellcheck='false'  /><div><button class='spectrum-cancel spectrum-hide-small'>Cancel</button><button class='spectrum-choose spectrum-hide-small'>Choose</button><button class='spectrum-cancel spectrum-show-small'>X</button><button class='spectrum-choose spectrum-show-small'>\u2714</button></div></div></div>"].join("")}(),
s=function(a,b){for(var c=[],d=0;d<a.length;d++){var f=d==b?" class='spectrum-pallet-active' ":"";c.push('<span style="background-color:'+tinycolor(a[d]).toHexString()+';"'+f+"></span>")}return c.join("")};if(m)e.fn.spectrum=function(a,b){if(typeof a=="string"){if(a=="get")return v[this.eq(0).data("spectrum.id")].get();return this.each(function(){var c=v[e(this).data("spectrum.id")];a=="show"&&c.show();a=="hide"&&c.hide();a=="set"&&c.set(b)})}return this.each(function(){var b=p(this,a);e(this).data("spectrum.id",
b.id)})},e.fn.spectrum.processOnLoad=!0,e.fn.spectrum.processOnLoadOpts={},e(function(){e.fn.spectrum.processOnLoad&&e("input[type=spectrum]").spectrum(e.fn.spectrum.processOnLoadOpts)});x.spectrum=p})(this,jQuery);
var tinycolor=function(){function x(a){var b={r:255,g:255,b:255},c=!1;typeof a=="string"&&(a=P(a));if(typeof a=="object")if(a.hasOwnProperty("r")&&a.hasOwnProperty("g")&&a.hasOwnProperty("b"))b={r:l(a.r,255)*255,g:l(a.g,255)*255,b:l(a.b,255)*255},c=!0;else if(a.hasOwnProperty("h")&&a.hasOwnProperty("s")&&a.hasOwnProperty("v")){var d=a.h;b=a.s;a=a.v;var f,g,e;d=l(d,360);b=l(b,100);a=l(a,100);c=Math.floor(d*6);var h=d*6-c;d=a*(1-b);var o=a*(1-h*b);b=a*(1-(1-h)*b);switch(c%6){case 0:f=a;g=b;e=d;break;
case 1:f=o;g=a;e=d;break;case 2:f=d;g=a;e=b;break;case 3:f=d;g=o;e=a;break;case 4:f=b;g=d;e=a;break;case 5:f=a,g=d,e=o}b={r:f*255,g:g*255,b:e*255};c=!0}else a.hasOwnProperty("h")&&a.hasOwnProperty("s")&&a.hasOwnProperty("l")&&(b=Q(a.h,a.s,a.l),c=!0);return{ok:c,r:Math.min(255,Math.max(b.r,0)),g:Math.min(255,Math.max(b.g,0)),b:Math.min(255,Math.max(b.b,0))}}function e(a,b,c){a=l(a,255);b=l(b,255);c=l(c,255);var d=Math.max(a,b,c),f=Math.min(a,b,c),e,q=(d+f)/2;if(d==f)e=f=0;else{var h=d-f;f=q>0.5?h/
(2-d-f):h/(d+f);switch(d){case a:e=(b-c)/h+(b<c?6:0);break;case b:e=(c-a)/h+2;break;case c:e=(a-b)/h+4}e/=6}return{h:e,s:f,l:q}}function Q(a,b,c){function d(a,b,c){c<0&&(c+=1);c>1&&(c-=1);if(c<1/6)return a+(b-a)*6*c;if(c<0.5)return b;if(c<2/3)return a+(b-a)*(2/3-c)*6;return a}a=l(a,360);b=l(b,100);c=l(c,100);if(b==0)c=b=a=c;else{var f=c<0.5?c*(1+b):c+b-c*b,e=2*c-f;c=d(e,f,a+1/3);b=d(e,f,a);a=d(e,f,a-1/3)}return{r:c*255,g:b*255,b:a*255}}function p(a,b,c){a=l(a,255);b=l(b,255);c=l(c,255);var d=Math.max(a,
b,c),e=Math.min(a,b,c),g,i=d-e;if(d==e)g=0;else{switch(d){case a:g=(b-c)/i+(b<c?6:0);break;case b:g=(c-a)/i+2;break;case c:g=(a-b)/i+4}g/=6}return{h:g,s:d==0?0:i/d,v:d}}function G(a,b,c){function d(a){return a.length==1?"0"+a:a}return[d(m(a).toString(16)),d(m(b).toString(16)),d(m(c).toString(16))].join("")}function l(a,b){var c=typeof a==="string"&&a.indexOf("%")!=-1;a=Math.min(b,Math.max(0,parseFloat(a)));c&&(a*=b/100);if(Math.abs(a-b)<1.0E-6)return 1;else if(a>1)return a%b/parseFloat(b);return a}
function n(a){return Math.min(1,Math.max(0,a))}function P(a){a=a.replace(t,"").replace(B,"").toLowerCase();H[a]&&(a=H[a]);if(a=="transparent")return{r:0,g:0,b:0,a:0};var b;if(b=s.rgb.exec(a))return{r:b[1],g:b[2],b:b[3]};if(b=s.hsl.exec(a))return{h:b[1],s:b[2],l:b[3]};if(b=s.hsv.exec(a))return{h:b[1],s:b[2],v:b[3]};if(b=s.hex6.exec(a))return{r:parseInt(b[1],16),g:parseInt(b[2],16),b:parseInt(b[3],16)};if(b=s.hex3.exec(a))return{r:parseInt(b[1]+""+b[1],16),g:parseInt(b[2]+""+b[2],16),b:parseInt(b[3]+
""+b[3],16)};return!1}var i=function(a){if(typeof a=="object"&&a.hasOwnProperty("_tc_id"))return a;a=x(a);var b=a.r,c=a.g,d=a.b;return{ok:a.ok,_tc_id:v++,toHsv:function(){return p(b,c,d)},toHsvString:function(){var a=p(b,c,d);return"hsv("+Math.round(a.h*360)+", "+Math.round(a.s*100)+"%, "+Math.round(a.v*100)+"%)"},toHsl:function(){return e(b,c,d)},toHslString:function(){var a=e(b,c,d);return"hsl("+Math.round(a.h*360)+", "+Math.round(a.s*100)+"%, "+Math.round(a.l*100)+"%)"},toHex:function(){return G(b,
c,d)},toHexString:function(){return"#"+G(b,c,d)},toRgb:function(){return{r:m(b),g:m(c),b:m(d)}},toRgbString:function(){return"rgb("+m(b)+", "+m(c)+", "+m(d)+")"},toName:function(){return U[G(b,d,c)]||!1}}};i.version="0.4";var t=/^[\s,#]+/,B=/\s+$/,v=0,m=Math.round;i.equals=function(a,b){return i(a).toHex()==i(b).toHex()};i.desaturate=function(a,b){var c=tinycolor(a).toHsl();c.s-=(b||10)/100;c.s=n(c.s);return tinycolor(c)};i.saturate=function(a,b){var c=tinycolor(a).toHsl();c.s+=(b||10)/100;c.s=n(c.s);
return tinycolor(c)};i.greyscale=function(a){return i.desaturate(a,100)};i.lighten=function(a,b){var c=tinycolor(a).toHsl();c.l+=(b||10)/100;c.l=n(c.l);return tinycolor(c)};i.darken=function(a,b){var c=tinycolor(a).toHsl();c.l-=(b||10)/100;c.l=n(c.l);return tinycolor(c)};i.triad=function(a){a=tinycolor(a).toRgb();return[tinycolor({r:a.r,g:a.g,b:a.b}),tinycolor({r:a.b,g:a.r,b:a.g}),tinycolor({r:a.g,g:a.b,b:a.r})]};i.tetrad=function(a){a=tinycolor(a).toRgb();return[tinycolor({r:a.r,g:a.g,b:a.b}),tinycolor({r:a.b,
g:a.r,b:a.g}),tinycolor({r:a.g,g:a.b,b:a.r}),tinycolor({r:a.r,g:a.b,b:a.r})]};i.monochromatic=function(a,b){b=b||6;for(var c=tinycolor(a).toHsv(),d=[];b--;)d.push(tinycolor(c)),c.v+=0.2,c.v%=1;return d};i.readable=function(a,b){var c=tinycolor(a).toRgb(),d=tinycolor(b).toRgb();return(d.r-c.r)*(d.r-c.r)+(d.g-c.g)*(d.g-c.g)+(d.b-c.b)*(d.b-c.b)>10404};var H=i.names={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",
blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",
darkslategray:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dodgerblue:"1e90ff",feldspar:"d19275",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",
lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslateblue:"8470ff",lightslategray:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",
mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",
powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",violetred:"d02090",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",
yellowgreen:"9acd32"},U=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[a[c]]=c);return b}(H),s={rgb:RegExp("rgb[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?"),hsl:RegExp("hsl[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?"),hsv:RegExp("hsv[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?"),
hex3:/^([0-9a-fA-F]{1})([0-9a-fA-F]{1})([0-9a-fA-F]{1})$/,hex6:/^([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$/};return i}();
